### ISSUE TITLE
Error message, when save configuration

### ISSUE THREAD

**Issue by andiukas** [chatziko/ha-google-cloud-stt#2]
Platform error tts.google_cloud_stt - No module named 'custom_components.google_cloud_stt.tts'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 887, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 316, in async_handle_reload_all
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Cannot quick reload all YAML configurations because the configuration is not valid: Platform error tts.google_cloud_stt - No module named 'custom_components.google_cloud_stt.tts'

**Comment by chatziko** [comment]
You need to change the yaml config to `stt:` instead of `tts:` (there was a typo in the readme)

**Comment by andiukas** [comment]
Thank you ;)
